path:
  # client PATH
  client: 'src/main/resources/calendarsync-385602-d5e29be74d4a.json'

calendar:
  config:
    # use calendar's ID which you want to add.
    calendarId: c13950256cbbc1ab12e036775c5579f088006ca0cf35060c755ec99c5229095f@group.calendar.google.com
    # you were setted applicationName
    applicationName: calendarsync
    timeZone: Asia/Taipei

spring:
  output:
    ansi:
      enabled:  always
  main:
    banner-mode: off
